name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Format with Black
        uses: psf/black@stable
        with:
          version: "23.3.0"
          options: "--check --verbose"